# Simple tic-tac-toe test config
# Use env_config as a single dict for single games
env_config:
  game_name: matching_pennies # kuhn_poker #connect_four #tic_tac_toe
  max_game_rounds: null

num_episodes: 1
seed: 42
use_ray: false
mode: llm_vs_random

agents:
  player_0:
    type: llm
    model: litellm_groq/llama3-8b-8192
  player_1:
    type: random

llm_backend:
  max_tokens: 250
  temperature: 0.1
  default_model: litellm_groq/llama3-8b-8192

log_level: DEBUG
tensorboard_logging: false  
